### PR TITLE
Combine the news and weekly functionality

### LINKED ISSUE #1732: Weekly Newsletter needs to be saved before being able to preview
It's kind of awkward that you currently have to save the weekly newsletter (therefore showing it on the homepage) before you're able to preview it. It would be nicer if when you press the preview button it would use the text inside the text field instead of the already saved text.

### PR DESCRIPTION
**Pull request by ysbrandB**
Combines the weekly functionality into the news functionality.
This way we will have a backlog of weekly overviews.
This also means we can now have a featured image in the weekly mail.
Also added a many to many relationship between news and events. This means that you can add the events to weeklies like u used too, but also to newsarticles (which will show up in a bar at the side). 

Fixes #1732, #1636 and #1138.

Newsadmin: 
image

Newsoverview:
image

Weekly edit:
image

Newsitem edit:
image

### CODE REVIEW

**Comment by Jessseee** [comment]
Why not merge it even further? Every weekly update could just be mixed in with the news articles instead of having them still separated as two different things.

**Comment by ysbrandB** [comment]
> Why not merge it even further? Every weekly update could just be mixed in with the news articles instead of having them still separated as two different things.

What would you merge further? The distinction in DB etc is necessary for sending the mails with the weekly and the differing views we use. In my personal opinion the distincion in the overview is also a nice to have.

**Comment by Jessseee** [comment]
I just feel like the overview page would just look weird because the news articles are not written frequently enough. So you will have one empty card for the news articles and a full card for the weekly newsletters, or at least one card with very outdated news articles. Maybe you could mix the two just in the UI. Then there is no need for the models to be merged, but it still makes for a more concise and up-to-date overview.

**Review by Jessseee — APPROVED** [review]
LGTM

**Review by Jessseee — CHANGES_REQUESTED** [review]
LNGTM

**Review by Jessseee — APPROVED** [review]
LGTM

**Pull request merged**
