### PR TITLE
Change syntax and refactor routes/web.php

### PR DESCRIPTION
**Pull request by Wilkuu-2**
**This draft pull request is for the main route file in the project. 
This means that testing and reviews need to be done with extra scrutiny.** 

Most of the changes are related to the new syntax, but this is a major opportunity to clean up the order and the grouping of the routes.

Most if not all routes were tested when changing the syntax, but I might also miss a few (there are a lot)/

### CODE REVIEW

**Comment by Wilkuu-2** [comment]
FYI The comments behind each route are the controller which the route was assigned to before the rewrite *(Each route has been rewritten using regex and the controller was left to be assigned)*. And serves a purpose for review and checking.

The comments will be removed before merging into master.

**Comment by Wilkuu-2** [comment]
FYI, The comments behind each route are the controller which the route was assigned to before the rewrite *(Each route has been rewritten using regex and the controller was left to be assigned)*. And serves a purpose for review and checking.

The comments will be removed before merging into master.

**Comment by Wilkuu-2** [comment]
image
## I checked every route manually, please review.

**Review by Jessseee — DISMISSED** [review]
LGTM

**Review by ysbrandB — APPROVED** [review]
LGTM

**Comment by ysbrandB** [comment]
> LGTM
Before we merge this we should merge the following first: https://github.com/saproto/saproto/pull/2184

**Comment by ysbrandB** [comment]
Will be merged with #2213

**Pull request closed without merging**
