### PR TITLE
Add functionality for rotating company logo's

### PR DESCRIPTION
**Pull request by WeeJeWel**

### CODE REVIEW

**Comment by Jessseee** [comment]
Thanks for the nice implementation! I will move the css from the blade file to the related scss file and I don't see any further problem with implementing this.

**Comment by WeeJeWel** [comment]
That's so cool!

**Comment by Jessseee** [comment]
Because I cannot add commits to your pull request I will have to close this PR and open a new one that will be merged as soon as possible.

**Pull request closed without merging**
