### PR TITLE
Add a orderline-like addone tool to achievements

### PR DESCRIPTION
**Pull request by ysbrandB**
also cleans up AchievementController, and implements search for Achievements

### CODE REVIEW

**Comment by Jessseee** [comment]
Please make responsive! 
image

**Review by Jessseee — CHANGES_REQUESTED** [review]
image
Please make responsive!!

**Comment by ysbrandB** [comment]
> image Please make responsive!!

Fixed :)

**Review by Jessseee — APPROVED** [review]
LGTM

**Pull request merged**
