### PR TITLE
Custom omnomcom sounds!

### PR DESCRIPTION
**Pull request by ysbrandB**
Implements #1385.
If you set a new custom sound (mp3, no larger than 200kb) in your dashboard, it will mute the cookiemonster video and play that sound instead!

### CODE REVIEW

**Comment by Jessseee** [comment]
I just want to say that I do not agree with this feature as it has huge potential for abuse and does not add anything of value, in my opinion.

**Comment by ysbrandB** [comment]
> I just want to say that I do not agree with this feature as it has huge potential for abuse and does not add anything of value, in my opinion

Would you feel differently when the board has to set your custom sound and therefore the abuse part of it is negated?

**Comment by Jessseee** [comment]
> > I just want to say that I do not agree with this feature as it has huge potential for abuse and does not add anything of value, in my opinion
> 
> Would you feel differently when the board has to set your custom sound and therefore the abuse part of it is negated?
> I think then the customization does add to the site just like we do with the custom welcome messages.

Yes, I think that would be fine.

**Comment by ysbrandB** [comment]
> > > I just want to say that I do not agree with this feature as it has huge potential for abuse and does not add anything of value, in my opinion
> > 
> > 
> > Would you feel differently when the board has to set your custom sound and therefore the abuse part of it is negated?
> > I think then the customization does add to the site just like we do with the custom welcome messages.
> 
> Yes, I think that would be fine.

Refactored so the board uploads a sound in the user admin instead for a member :)

**Review by Frank-Bosman — APPROVED** [review]
Ziet er goed uit!!

**Pull request merged**
